apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring-app-deployment
  lables:
      app: java-spring-app
spec:
  template:
    metadata:
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: java-spring-app
          image: devopstech24/java-spring-app-ci-pipeline:60
          # ports:
          #   - containerPort: 8080
  replicas: 2
  # selector:
  #   matchLabels:
  #     app: java-spring-app
