apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring-app-deployment
  lables:
      # name: java-spring-app-deployment
      app: myapp
      type: front-end
spec:
  template:
    metadata:
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: java-spring-app
          image: devopstech24/java-spring-app-ci-pipeline:60
  replicas: 2
