apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring-app-deployment
  labels:
    app: java-spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-spring-app
  template:
    metadata:
      labels:
        app: java-spring-app
    spec:
      containers:
      - name: java-spring-app
        image: devopstech24/java-spring-app-ci-pipeline:60
        ports:
        - containerPort: 8080
