---
apiVersion: v1
kind: Service
metadata:
  name: java-spring-app-service
  labels:
      name: java-spring-app-service
      app: java-spring-app
spec:
  type: NodePort
  ports:
   -  targetPort: 8080
      port: 8080
  selector: 
      name: java-spring-app-pod
      app: java-spring-app
