apiVersion: v1
kind: Service
metadata:
  name: java-spring-app-service
  labels:
    app: java-spring-app 
spec:
  selector:
    app: java-spring-app

  ports:
    - port: 8080
      targetPort: 8080

  type: NodePort 
  # LoadBalancer