apiVersion: v1
kind: Service
metadata:
  name: java-spring-app-service
spec:
  selector:
    app: java-spring-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
