apiVersion: v1
kind: Service
metadata:
  name: java-spring-application-service
  labels:
      name: java-spring-application-service
      app:  myapp
spec:
  type: NodePort
  ports:
   -  targetPort: 8080
      port: 8080
      nodePort: 30008
  selector:
      app: myapp
      type: front-end
